/* elfuse VM launch: bring-up + GDB + run loop + teardown
 *
 * Copyright 2026 elfuse contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Implementation of elfuse_launch (contract and caller/callee ownership in
 * launch.h). Extracted from src/main.c so the positional-ELF CLI and other
 * launchers (e.g. the OCI run helper) share one bring-up path.
 *
 * shim_blob.h is included here, not in src/main.c, so the static
 * shim_bin / shim_bin_len blob has a single object definition site.
 */

#include "launch.h"

#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "core/bootstrap.h"
#include "core/guest.h"
#include "core/shim-globals.h"
#include "core/sysroot.h"

#include "runtime/futex.h" /* futex_interrupt_request */
#include "runtime/thread.h"
#include "syscall/path.h"
#include "syscall/poll.h" /* wakeup_pipe_signal */
#include "syscall/proc.h"

#include "debug/gdbstub.h"
#include "debug/log.h"
#include "debug/syscall-hist.h"

/* Embedded shim binary (generated by xxd -i from shim.bin). */
#include "shim_blob.h"

/* The shim code slot in the infra reserve is sized tight (INFRA_SHIM_SLOT, a
 * few x the current blob) so the rest of the reserve goes to the page-table
 * pool. If the shim ever outgrows the slot it would overlap the shim-data
 * block; fail the build loudly rather than corrupt memory at boot. Enlarge
 * INFRA_SHIM_SLOT (and shrink the pool to match) if this fires.
 */
_Static_assert(sizeof(shim_bin) <= INFRA_SHIM_SLOT,
               "shim blob exceeds its infra slot; bump INFRA_SHIM_SLOT");

int elfuse_launch(const launch_args_t *args)
{
    if (!args) {
        log_error("elfuse_launch: NULL args");
        return 1;
    }

    extern char **environ;
    char **envp_use = args->envp ? args->envp : environ;

    guest_t g;
    bool guest_initialized = false;
    guest_bootstrap_t boot;
    /* Track the temp flag locally: elfuse_launch owns the post-prepare
     * unlink of a FUSE-materialized temp, but the caller's launch_args_t
     * is const and its copy is discarded after the call anyway.
     */
    bool elf_host_temp = args->elf_host_temp;
    /* The guest-visible entrypoint path is argv[0]; elf_path is the
     * resolved host path to that binary. They differ when path
     * translation or a FUSE-materialized temp is involved.
     */
    const char *elf_guest_path = (args->guest_argc > 0 && args->guest_argv)
                                     ? args->guest_argv[0]
                                     : args->elf_path;

    /* Stage --user before bring-up: prepare's proc_init re-seeds the identity
     * state, and build_linux_stack snapshots it into auxv AT_UID/AT_GID.
     * Setting the ids after prepare would leave getauxval() reporting the
     * default identity while getuid() reports the requested one.
     */
    if (args->has_creds)
        proc_set_initial_ids(args->uid, args->gid);

    if (guest_bootstrap_prepare(
            &g, args->elf_path, elf_host_temp, elf_guest_path, args->sysroot,
            args->guest_argc, args->guest_argv, envp_use, shim_bin,
            shim_bin_len, args->verbose, &guest_initialized, &boot) < 0)
        goto fail;

    /* A FUSE-materialized temp has been loaded; drop it once the guest
     * has its own mapping, unless Rosetta still needs the reopenable
     * host path.
     */
    if (elf_host_temp && !g.is_rosetta) {
        unlink(args->elf_path);
        elf_host_temp = false;
    }

    /* Reject GDB for a Rosetta (x86_64) guest here, not just in main(): the
     * stub exposes the aarch64 shim's register/memory view, which is the wrong
     * architecture for a Rosetta-translated x86_64 guest. main() rejects it up
     * front via a static ELF probe, but enforcing it in elfuse_launch (once
     * bring-up has set g.is_rosetta) makes every caller inherit the constraint,
     * including the planned OCI run helper.
     */
    if (args->gdb_port > 0 && g.is_rosetta) {
        log_error("--gdb is not supported for x86_64 (Rosetta) guests");
        goto fail;
    }

    if (args->sysroot) {
        bool case_sensitive = true;
        bool case_preserving = true;
        if (sysroot_probe_case_sensitivity(args->sysroot, &case_sensitive,
                                           &case_preserving) == 0)
            proc_set_sysroot_casefold(case_preserving && !case_sensitive);
        else
            proc_set_sysroot_casefold(false);
    } else {
        proc_set_sysroot_casefold(false);
    }

    /* Apply the guest's initial working directory. The guest cwd IS the host
     * process cwd (sys_chdir translates a guest path and calls host chdir),
     * so --workdir DIR does the same: translate DIR against the sysroot (now
     * that casefold is configured above) and chdir to the resulting host path,
     * then refresh the cached guest-visible cwd so the first getcwd sees DIR.
     * This mirrors the plain real-directory branch of sys_chdir; FUSE-mounted
     * or /proc-virtual workdirs are not supported through this flag (neither
     * is a realistic image WorkingDir).
     */
    if (args->cwd_guest && args->cwd_guest[0] != '\0') {
        path_translation_t tx;
        if (path_translate_at(LINUX_AT_FDCWD, args->cwd_guest, PATH_TR_NONE,
                              &tx) < 0) {
            log_error("failed to resolve working directory %s: %s",
                      args->cwd_guest, strerror(errno));
            goto fail;
        }
        if (chdir(tx.host_path) < 0) {
            log_error("failed to set working directory %s: %s", args->cwd_guest,
                      strerror(errno));
            goto fail;
        }
        if (proc_cwd_refresh() < 0)
            proc_cwd_invalidate();
    }

    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    if (guest_bootstrap_create_vcpu(&g, &boot, args->verbose, &vcpu, &vexit) <
        0)
        goto fail;

    /* GDB setup must happen before the first run so entry-stop and
     * hardware breakpoints can affect the initial vCPU.
     */
    if (args->gdb_port > 0) {
        if (gdb_stub_init(args->gdb_port, &g) < 0) {
            log_error("failed to initialize GDB stub");
            goto fail;
        }
        gdb_stub_sync_debug_regs(vcpu);
        if (args->gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    }

    /* vcpu_run_loop owns guest execution until exit, fatal signal, or timeout.
     */
    int exit_code =
        vcpu_run_loop(vcpu, vexit, &g, args->verbose, args->timeout_sec, NULL);

    /* Tear down debugger state before joining workers: a worker parked in
     * gdb_stub_handle_stop() stays active (not deactivated) until this
     * broadcasts resume_cond, so joining first would just time out and
     * detach it while it is still paused.
     */
    gdb_stub_shutdown();

    /* Join worker vCPU threads before guest_destroy unmaps the guest slab: a
     * sibling still mid-iteration in its own run loop would fault on freed
     * guest memory and crash the host with SIGSEGV, masking the real exit
     * code. The join is a no-op once workers have wound down (the common
     * single-threaded case).
     *
     * vcpu_run_loop can also return via a bare break (alarm timeout 124, a
     * fatal default-disposition signal, or ELR_EL1==0) with no one having
     * requested exit_group or kicked the siblings out of hv_vcpu_run. Mirror
     * guest_destroy's request-interrupt prefix here first; otherwise this join
     * burns its full poll cap and detaches every worker, and guest_destroy's
     * own interrupt-join skips them (it honors join_abandoned), leaving live
     * pthreads to fault on the imminent unmap.
     */
    if (!proc_exit_group_requested())
        proc_request_exit_group(0);
    futex_interrupt_request();
    wakeup_pipe_signal();
    thread_interrupt_all();
    /* Workers parked on internal condvars (fork barrier, ptrace stop/wait)
     * see neither the pipe nor the vCPU kick; broadcast so they re-check the
     * exit-group flag and terminate before the join below gives up on them.
     */
    thread_wake_exit_waiters();
    thread_join_workers();

    /* Diagnostic counter dump runs before guest_destroy so the
     * shim_data mapping is still valid. ELFUSE_SHIM_STATS is the gate;
     * an unset variable produces no output.
     */
    if (shim_globals_stats_enabled())
        shim_globals_counters_dump(&g);

    /* Dump the startup histogram before guest_destroy so any
     * cleanup-path syscalls (closing host fds, unmapping the slab) do
     * not appear in the captured set. The dump is a no-op when
     * ELFUSE_STARTUP_TRACE=syscalls was not requested.
     */
    syscall_hist_dump();

    if (guest_initialized)
        guest_destroy(&g);

    /* Rosetta guests keep the FUSE-materialized temp alive for the whole run
     * (the translator reopens the host path); drop it now that the guest is
     * gone so repeated Rosetta launches do not accumulate temp files.
     */
    if (elf_host_temp)
        unlink(args->elf_path);

    return exit_code;

fail:
    /* Bring-up failed: unwind whatever exists so far. The caller owns
     * pre-prepare failures; from the prepare call onward the temp unlink
     * is ours.
     */
    if (guest_initialized)
        guest_destroy(&g);
    if (elf_host_temp)
        unlink(args->elf_path);
    return 1;
}
